export const GET_REPOS = "GET_REPOS";
export const GET_REPOS_SUCCESS = `${GET_REPOS}_SUCCESS`;
export const GET_REPOS_FAILED = `${GET_REPOS}_FAILED`;

export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORGANIZATIONS_SUCCESS = `${GET_ORGANIZATIONS}_SUCCESS`;
export const GET_ORGANIZATIONS_FAILED = `${GET_ORGANIZATIONS}_FAILED`;